"""
Exact audit of the full signal covariance: every spectrum type, every bin pair.

Motivated by the EB factor-2 error found 10 Aug 2026, which survived years of
MC verification, gradient finite-difference checks and covariance-symmetry
checks -- all of which are blind to a multiplicative error in a single kernel.
This test is not blind to one: it compares build_signal_cov against the EXACT
covariance, with no fitted prefactors and no Monte-Carlo noise floor.

Method: the (T,Q,U) maps are LINEAR in the alm real degrees of freedom,

    x = sum_dof a_dof * v_dof,     v_dof = alm2map(unit alm),

so the covariance is exactly sum_dof,dof' <a_dof a_dof'> v_dof v_dof'^T, with
<a a'> read straight off the input spectra (variance C_l for m=0, C_l/2 for the
Re and Im parts when m>0).  Both sides are linear in the spectra, so the input
spectral matrix need not be positive definite -- the cross-spectra are set to
distinct, deliberately asymmetric values to expose any pair-ordering mistake.

Because the truth is generated by healpy's own alm2map, this also pins the sign
and normalization conventions (the HEALPix a_E = -Re(...) convention, the TB
signs) to the same ones Almanac uses.

Configuration: n_T=2, n_P=2, include_TB, include_EB -- the smallest case that
exercises auto-bins, cross-bins and both orderings of every cross-spectrum.

Run from repo root or tests/:
    python3 tests/test_covariance_exact.py
"""

import sys, os
import numpy as np
import healpy as hp

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from pixel_likelihood import PixelLikelihood

PASS = "\033[92mPASS\033[0m"
FAIL = "\033[91mFAIL\033[0m"
_FAILURES = []

TOL = 1e-10


def check(name, cond, detail=""):
    if cond:
        print(f"  {PASS}  {name}")
    else:
        print(f"  {FAIL}  {name}" + (f": {detail}" if detail else ""))
        _FAILURES.append(name)


NSIDE, LMIN, LMAX = 4, 2, 7
NPIX = hp.nside2npix(NSIDE)
N_T, N_P = 2, 2
ND = N_T * NPIX + N_P * 2 * NPIX
SZ = hp.Alm.getsize(LMAX)
ZERO = np.zeros(SZ, dtype=complex)

FIELDS = ['T0', 'T1', 'E0', 'B0', 'E1', 'B1']

# Distinct values throughout; cross-bin entries deliberately asymmetric
# (C^{T0E1} != C^{T1E0}, C^{E0B1} != C^{E1B0}) to catch pair-ordering errors.
SPEC = {
    'TT': {('T0', 'T0'): 1.0e-6, ('T1', 'T1'): 2.0e-6, ('T0', 'T1'): 0.30e-6},
    'EE': {('E0', 'E0'): 3.0e-6, ('E1', 'E1'): 1.5e-6, ('E0', 'E1'): 0.40e-6},
    'BB': {('B0', 'B0'): 0.8e-6, ('B1', 'B1'): 0.6e-6, ('B0', 'B1'): 0.20e-6},
    'TE': {('T0', 'E0'): 0.50e-6, ('T0', 'E1'): 0.25e-6,
           ('T1', 'E0'): 0.15e-6, ('T1', 'E1'): 0.35e-6},
    'TB': {('T0', 'B0'): 0.12e-6, ('T0', 'B1'): -0.09e-6,
           ('T1', 'B0'): 0.07e-6, ('T1', 'B1'): 0.05e-6},
    'EB': {('E0', 'B0'): 0.20e-6, ('E0', 'B1'): 0.10e-6,
           ('E1', 'B0'): -0.15e-6, ('E1', 'B1'): 0.05e-6},
}


def _place(field, arrs):
    v = np.zeros(ND)
    k = int(field[1])
    if field[0] == 'T':
        v[k * NPIX:(k + 1) * NPIX] = arrs[0]
    else:
        s = N_T * NPIX + k * 2 * NPIX
        v[s:s + NPIX] = arrs[0]
        v[s + NPIX:s + 2 * NPIX] = arrs[1]
    return v


def _basis(l, m, field, part):
    a = np.zeros(SZ, dtype=complex)
    a[hp.Alm.getidx(LMAX, l, m)] = 1.0 if part == 're' else 1.0j
    if field[0] == 'T':
        return _place(field, [hp.alm2map(a, nside=NSIDE, lmax=LMAX)])
    almE, almB = (a, ZERO) if field[0] == 'E' else (ZERO, a)
    _, Q, U = hp.alm2map([ZERO, almE, almB], nside=NSIDE, lmax=LMAX)
    return _place(field, [Q, U])


print("Building exact alm->map basis...")
BASIS = {}
for _l in range(LMIN, LMAX + 1):
    for _m in range(_l + 1):
        for _p in (['re'] if _m == 0 else ['re', 'im']):
            for _f in FIELDS:
                BASIS[(_l, _m, _p, _f)] = _basis(_l, _m, _f, _p)


def exact_cov(entries):
    """entries: {(field_a, field_b): C_l}; symmetrized internally."""
    S = {}
    for (fa, fb), val in entries.items():
        S[(fa, fb)] = S[(fb, fa)] = val
    cov = np.zeros((ND, ND))
    for l in range(LMIN, LMAX + 1):
        for m in range(l + 1):
            parts = ['re'] if m == 0 else ['re', 'im']
            w = 1.0 if m == 0 else 0.5
            for part in parts:
                for (fa, fb), c in S.items():
                    if c != 0.0:
                        cov += w * c * np.outer(BASIS[(l, m, part, fa)],
                                                BASIS[(l, m, part, fb)])
    return cov


def rel_rms(a, b):
    return np.sqrt(np.mean((a - b) ** 2)) / np.sqrt(np.mean(b ** 2))


def _make_lik():
    rng = np.random.default_rng(0)
    s = 1e-3
    N = np.full(NPIX, s ** 2 * 4 * np.pi / NPIX)
    return PixelLikelihood.from_arrays(
        d_T_list=[rng.standard_normal(NPIX) * s for _ in range(N_T)],
        d_Q_list=[rng.standard_normal(NPIX) * s for _ in range(N_P)],
        d_U_list=[rng.standard_normal(NPIX) * s for _ in range(N_P)],
        obs_pix=np.arange(NPIX), nside=NSIDE,
        N_T_list=[N] * N_T, N_Q_list=[N] * N_P, N_U_list=[N] * N_P,
        lmin=LMIN, lmax=LMAX, band_edges=np.array([LMIN, LMAX + 1]),
        band_model='Cl', include_TB=True, include_EB=True)


def test_pair_counts(lik):
    """EB must use ordered pairs; EE/BB/TT unordered; TE/TB ordered."""
    print("\nTest 1: parameter pair structure")
    got = {spec: len(pairs) for spec, pairs in lik.layout.spec_groups()}
    want = {'TT': N_T * (N_T + 1) // 2, 'TE': N_T * N_P, 'TB': N_T * N_P,
            'EE': N_P * (N_P + 1) // 2, 'BB': N_P * (N_P + 1) // 2,
            'EB': N_P * N_P}
    for spec in ['TT', 'TE', 'TB', 'EE', 'BB', 'EB']:
        check(f"{spec}: {want[spec]} pairs", got.get(spec) == want[spec],
              f"got {got.get(spec)}, want {want[spec]}")


def test_covariance_exact(lik):
    """build_signal_cov must equal the exact covariance, per type and jointly."""
    print("\nTest 2: signal covariance vs exact alm->map covariance")

    def params(specs):
        p = np.zeros(lik.layout.n_params)
        for spec in specs:
            for (fa, fb), val in SPEC[spec].items():
                p[lik.layout.index(spec, int(fa[1]), int(fb[1]), 0)] = val
        return p

    for spec in ['TT', 'EE', 'BB', 'TE', 'TB', 'EB']:
        r = rel_rms(lik.build_signal_cov(params([spec])), exact_cov(SPEC[spec]))
        print(f"    {spec} alone : rel residual = {r:.3e}")
        check(f"{spec} covariance exact", r < TOL, f"{r:.3e}")

    joint = {}
    for spec in SPEC:
        joint.update(SPEC[spec])
    r = rel_rms(lik.build_signal_cov(params(list(SPEC))), exact_cov(joint))
    print(f"    all six    : rel residual = {r:.3e}")
    check("joint covariance exact", r < TOL, f"{r:.3e}")


def test_kernel_amplitudes(lik):
    """Each kernel must equal the exact d(Cov)/d(param) -- amplitude AND shape.

    A factor-2-style error shows up here as amp != 1 with shape residual 0;
    a wrong kernel shows up as a nonzero shape residual.
    """
    print("\nTest 3: per-parameter kernel vs exact derivative")
    worst_amp, worst_shape, worst_name = 0.0, 0.0, ''
    for spec in ['TT', 'EE', 'BB', 'TE', 'TB', 'EB']:
        for (fa, fb) in sorted(SPEC[spec]):
            ex = exact_cov({(fa, fb): 1.0})
            K = lik._get_kernel(lik.layout.index(spec, int(fa[1]), int(fb[1]), 0))
            amp = np.dot(K.ravel(), ex.ravel()) / np.dot(ex.ravel(), ex.ravel())
            shape = rel_rms(K, ex)
            if abs(amp - 1.0) > worst_amp:
                worst_amp, worst_name = abs(amp - 1.0), f"{spec} {fa}x{fb}"
            worst_shape = max(worst_shape, shape)
    print(f"    worst |amp - 1| = {worst_amp:.3e} ({worst_name or 'none'})")
    print(f"    worst shape residual = {worst_shape:.3e}")
    check("all kernel amplitudes == 1", worst_amp < TOL, f"{worst_amp:.3e}")
    check("all kernel shapes exact", worst_shape < TOL, f"{worst_shape:.3e}")


if __name__ == '__main__':
    print("=" * 70)
    print("Exact signal-covariance audit (n_T=2, n_P=2, TB and EB on)")
    print("=" * 70)
    _lik = _make_lik()
    test_pair_counts(_lik)
    test_covariance_exact(_lik)
    test_kernel_amplitudes(_lik)
    print()
    if _FAILURES:
        print(f"{FAIL}: {len(_FAILURES)} check(s) failed: {', '.join(_FAILURES)}")
        sys.exit(1)
    print(f"{PASS}: all checks passed")
